version: '3.8'  # Specify the Compose file format version

services:
  customers:
    build:
      context: ./customers  # Path to the customers service folder
    ports:
      - "5001:5001"         # Map port 5001 to the host
    volumes:
      - ./customers:/app    # Mount the service directory for live updates
      - ./customers/database:/data
    environment:
      - FLASK_ENV=development

  inventory:
    build:
      context: ./inventory  # Path to the inventory service folder
    ports:
      - "5002:5002"         # Map port 5002 to the host
    volumes:
      - ./inventory:/app
      - ./inventory/database:/data
    environment:
      - FLASK_ENV=development

  sales:
    build:
      context: ./sales       # Path to the sales service folder
    ports:
      - "5003:5003"          # Map port 5003 to the host
    volumes:
      - ./sales:/app
      - ./sales/database:/data
    environment:
      - FLASK_ENV=development

  reviews:
    build:
      context: ./reviews     # Path to the reviews service folder
    ports:
      - "5004:5004"          # Map port 5004 to the host
    volumes:
      - ./reviews:/app
      - ./reviews/database:/data
    environment:
      - FLASK_ENV=development
